Process 0: Solving linear variational problem.
Process 1: Solving linear variational problem.
Process 7: Solving linear variational problem.
Process 8: Solving linear variational problem.
Process 6: Solving linear variational problem.
Process 2: Solving linear variational problem.
Process 3: Solving linear variational problem.
Process 5: Solving linear variational problem.
Process 4: Solving linear variational problem.
Process 1: No Jacobian form specified for nonlinear variational problem.
Process 1: Differentiating residual form F to obtain Jacobian J = F'.
Process 4: No Jacobian form specified for nonlinear variational problem.
Process 4: Differentiating residual form F to obtain Jacobian J = F'.
Process 5: No Jacobian form specified for nonlinear variational problem.
Process 5: Differentiating residual form F to obtain Jacobian J = F'.
Process 2: No Jacobian form specified for nonlinear variational problem.
Process 2: Differentiating residual form F to obtain Jacobian J = F'.
Process 8: No Jacobian form specified for nonlinear variational problem.
Process 8: Differentiating residual form F to obtain Jacobian J = F'.
Process 7: No Jacobian form specified for nonlinear variational problem.
Process 7: Differentiating residual form F to obtain Jacobian J = F'.
Process 0: No Jacobian form specified for nonlinear variational problem.
Process 0: Differentiating residual form F to obtain Jacobian J = F'.
Process 3: No Jacobian form specified for nonlinear variational problem.
Process 3: Differentiating residual form F to obtain Jacobian J = F'.
Process 6: No Jacobian form specified for nonlinear variational problem.
Process 6: Differentiating residual form F to obtain Jacobian J = F'.
Process 0: Solving nonlinear variational problem.
Process 6: Solving nonlinear variational problem.
Process 2: Solving nonlinear variational problem.
Process 8: Solving nonlinear variational problem.Process 4: Solving nonlinear variational problem.

Process 3: Solving nonlinear variational problem.
Process 1: Solving nonlinear variational problem.
Process 5: Solving nonlinear variational problem.
Process 7: Solving nonlinear variational problem.
  Process 0: Newton iteration 0: r (abs) = 8.517e+06 (tol = 1.000e-08) r (rel) = 1.000e+00 (tol = 1.000e-08)
Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4494, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 7
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4469, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 4
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4639, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 2
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4473, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 5
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4512, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 6
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4664, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4503, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 1
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4427, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 8
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

Relative path:  /mnt/biherrera/alveolar-perfusion-transport-modeling
Imported src files
Starting...
Model initialised
Mesh imported
Coordinates have shape  (4486, 3)
Mesh imported
Mesh refined
Starting (P) simulation
began sim_p
Instancing boundaries
gamma_in.dir_min =  0.09939099848270416
gamma_in.dir_max =  39.894161224365234
gamma_out.dir_min =  0.09939099848270416
gamma_out.dir_max =  39.894161224365234
gamma_air.dir_min_y =  0.09558500349521637
gamma_air.dir_max_y =  39.895729064941406
gamma_air.dir_min_z =  0.1048400029540062
gamma_air.dir_max_z =  39.89208984375
boundaries instanced
self.f_dim = 2
self.vecf_dim = 1
P problem solved
u problem solved
Saving solutions
saved
(P) simulation done
Starting (T) simulation
began sim_t, with solver =  bicgstab
Solving with solver = bicgstab and without preconditioner.
Traceback (most recent call last):
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/tests/cluster/40_h_repaired_solvers/mumps_9.py", line 41, in <module>
    x = model.sim_t(hb=False, save=True, solver="bicgstab")
  File "/mnt/biherrera/alveolar-perfusion-transport-modeling/src/model.py", line 455, in sim_t
    solve(
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 220, in solve
    _solve_varproblem(*args, **kwargs)
  File "/home/biherrera/miniconda3/lib/python3.9/site-packages/dolfin/fem/solving.py", line 266, in _solve_varproblem
    solver.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to successfully call PETSc function 'MatXIJSetPreallocation'.
*** Reason:  PETSc error code is: 4031 ((null)).
*** Where:   This error was encountered inside /home/conda/feedstock_root/build_artifacts/fenics-pkgs_1653063982664/work/dolfin/dolfin/la/PETScMatrix.cpp.
*** Process: 3
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  ba376b6aebd7a9bc089be46b50bdd9f5c548fb91
*** -------------------------------------------------------------------------

